GET http://127.0.0.1:3000/contacts/
Accept: application/json

###

GET http://127.0.0.1:3000/contacts/2
Accept: application/json

###

POST http://127.0.0.1:3000/contacts/
Content-Type: application/json

{
  "name": "Mr Goon",
  "email": "goon@mail.com"
}

###

PUT http://127.0.0.1:3000/contacts/1
Content-Type: application/json

{
  "name": "Mr Goon",
  "email": "goon@mail.com"
}

###

DELETE http://127.0.0.1:3000/contacts/1
Accept: application/json

###
